### ISSUE TITLE
Add timeout/delay between searching for customer and creating new one

### ISSUE THREAD

**Issue by helgatheviking** [kathyisawesome/woo3pd-helpscout#11]
Have seen a few times that this call for customers:

https://github.com/kathyisawesome/woo3pd-helpscout/blob/master/src/Api/Helpscout.php#L318

returns no matches, but trying to create the new customer throws an error: https://github.com/kathyisawesome/woo3pd-helpscout/blob/master/src/Api/Helpscout.php#L355

HelpScout supports suggests putting in a little delay between the reception of the webhook and the processing of the webhook. This gives HS time on their side to be sure the customer is created. (Not 100% clear on why they are creating the customer since the email comes from Woo, but that was their suggestion).

**Comment by Preciousomonze** [comment]
Who's using this plugin?
Just you?🌝

**Comment by helgatheviking** [comment]
yes. as far as i know. gotta write a blog post about it some day and tell the other devs it even exists.

**Comment by Preciousomonze** [comment]
😂😂 You still down for us putting it on wp.org?

**Comment by helgatheviking** [comment]
it's so limited in it's scope (it only works for plugins sold at woocommerce.com and only with HelpScout) I don't see a strong need to host it at .org.

**Comment by Preciousomonze** [comment]
Yh I know, you never can tell how useful it'll be, same way i felt my phone validator plugin was pointless, the turn out won't be as much, but it'll still be okay.
